### PR TITLE
Fix comparison operation

### LINKED ISSUE #9: When setting a value in a store, should the emitter emit if the value has not changed?
As it stands, calling `someStore.set('someProperty')(someValue)` will always emit, even if `someValue` is already equal to `someStore.get('someProperty')` before the call. This can lead to infinite emitting loops in the following circumstance:

```typescript
tradeTickerStore.on('selectedSymbol')
    .subscribe( symbol => 
        appStore.set('currentSymbol')(symbol) 
    );

appStore.on('currentSymbol')  //update all stores upon setting the general application state
    .subscribe( symbol => {
        orderBookStore.set('symbol')(symbol);
        tradesStore.set('symbol')(symbol);
        candlesStore.set('symbol')(symbol);
        tradeTickerStore.set('selectedSymbol')(symbol); // <-- causes a never ending emit loop.
    });    
```

While this can be avoided by a conditional clause before calling set('')(), it's convenient it be done inside of set('')() as it avoids having to repeat the condition everywhere it is needed and it also avoids firing an emit event when the value has not changed.

### PR DESCRIPTION
**Pull request by 8th713**
Currently the implementation of the equals function depends on the internal API of Immutable.js and is not secure.
Remove support for specific libraries. Instead can replace comparison operations.

Close #9

### CODE REVIEW

**Comment by bcherny** [comment]
@8th713 Thanks for the PR! Can you help me understand what you mean by "not secure"? The goal was to have ImmutableJS support out of the box, without having to include all of ImmutableJS in this package. You're right about using the internal API being bad, but we can update it when ImmutableJS does - in terms of costs vs. benefits, the benefits of keeping the bundle lean and providing ImmutableJS support out of the box far outweighs the cost of relying on this particular internal API I think.

Do you have a use case for a custom equality check?

**Comment by 8th713** [comment]
> Can you help me understand what you mean by "not secure"?

Sorry, I am not good at English. I just wanted to say that I should not rely on a internal API.

> Do you have a use case for a custom equality check?

It helps those who use immutable collection libraries other than ImmutableJS like [list](https://github.com/funkia/list).
Or you may want to compare Date objects using the `getDay` method.

In my opinion equality of values depends on use case. Some people say `0` and` -0` are equal. But another person would say that `0` and` -0` are not equal.

**Comment by bcherny** [comment]
@8th713 I couldn't agree more. My hope was to include some non-controversial equality checks by default, eg. Immutable. Undux's main goal is be easy to use safely. What do you think?

**Comment by 8th713** [comment]
I understand.
I will closing this PR and submit a new PR to fix #9.

**Pull request closed without merging**
